### PR TITLE
Fix grammar in readme.

### PR DESCRIPTION
**Pull request by sorribas**

### CODE REVIEW

**Comment by LinusU** [comment]
Duplicate of #10 :sandal:

**Comment by thanpolas** [comment]
dup with #10

**Comment by LinusU** [comment]
@thanpolas Duplicate of https://github.com/mafintosh/are-feross-and-mafintosh-stuck-in-an-elevator/pull/11#issuecomment-127989882

**Comment by sorribas** [comment]
Oh yeah, my bad.

**Pull request closed without merging**
